### ISSUE TITLE
wire plugin for rjs does not include spec

### ISSUE THREAD

**Issue by DaniHaag** [pieterv/rjs-wire#1]
if I use the wire plugin with rjs 2.1.5. The whole build works fine, but it does not add the spec files. it does insert the dependencies of the spec.
 The reason seems to be, that the specs do not return values and rjs only adds the returned values.

the specs i use look like this:
 define({
 module1: {...},
 plugins: {..}
 })

**Comment by pieterv** [comment]
Could i ask what version of the wire rjs plugin you are using? This is the latest version: https://github.com/pieter-vanderwerff/wire/blob/rjs-build/builder/rjs.js

Are you seeing this behaviour when running this projects example build, specifically when running this build command: `./node_modules/.bin/r.js -o ./build.via-wire.js`? For my current setup i am seeing the spec files come through in the final built file, as you can see in this built file: https://github.com/pieter-vanderwerff/rjs-wire/blob/master/build/via-wire.js#L3629

My understanding of the `define( {} )` syntax is that its just a short way of writing `define( function() { return {}; } )` so internally it should be receiving the object as the modules return value.

**Comment by DaniHaag** [comment]
Hi Pieter, 
I have used a custom setup with a downloaded 2.1.5 r.js and the current wire version. The reason is, I seem to miss a step in building your project. The install step works well, but the run does not work at all. 
I tried it with node ./node_modules/.bin/r.js -o ./build.via-wire.js, I started node and added the script but I seem not to be able to run it. It always returns errors. Could you give me another hint what I might be missing?

in the command line: 
node ./node_modules/.bin/r.js -o .\build.via-init.js

GitHub\rjs-wire\node_modules.bin\r.js:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

in Node:

> ./node_modules/.bin/r.js -o ./build.via-wire.js
> Invalid REPL keyword

**Comment by pieterv** [comment]
Hey,

Just to check, can you verify you are following these steps to get the project running.
1. checkout the project `git clone https://github.com/pieter-vanderwerff/rjs-wire.git`
2. navigate to project directory `cd rjs-wire/`
3. install node modules (rjs) `npm install`
4. install bower components (wire) `bower install`
5. run the build from the project directory `node ./node_modules/.bin/r.js -o ./build.via-wire.js`

Let me know if that still doesn't work, but the error above looks to me like something is breaking before it even runs the rjs-wire build plugin.

I have only tested this on Mac OS with node v0.8.20.

**Comment by DaniHaag** [comment]
Hi Pieter, 
thanks for clarifiying this. I thought npm was an alternative to bower. So I now installed bower and did a bower install. 
So step 1-4 have been successful. 
But I still get the same error in Step 5.

C:\Dokumente und Einstellungen\me\Eigene Dateien\GitHub\rjs-wire>node ./node_m
odules/.bin/r.js -o ./build.via-wire.js

C:\Dokumente und Einstellungen\me\Eigene Dateien\GitHub\rjs-wire\node_modules\
.bin\r.js:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

C:\Dokumente und Einstellungen\me\Eigene Dateien\GitHub\rjs-wire>node ./node_m
odules/.bin/r.js -o ./build.via-wire.js

**Comment by pieterv** [comment]
Hmm interesting, im assuming you are using windows? The error looks to me like an environmental problem, but sorry im not much help as i don't have a windows machine to test or know very much about windows.

The only thing i can think of is trying some variations of the path?
- `node ./node_modules/.bin/r.js -o build.via-wire.js` 
- `node ./node_modules/.bin/r.js -o .\build.via-wire.js`
- `node .\node_modules\.bin\r.js -o .\build.via-wire.js`

Sorry im not much help with this problem. Maybe there is more info in the [rjs repo](https://github.com/jrburke/r.js).

**Comment by DaniHaag** [comment]
Hi Pieter,

I got it to run now. On windows you need to go directly to the r.js file. It is 
node ./node_modules/requirejs/bin/r.js -o ./build.via-wire.js type ./build.via-wire.js

It needs unix or possibly cygwin to run your command.
I will investigate further on my issue and will update this thread if I find out anything.

**Comment by pieterv** [comment]
Thats good news :)

Yes please let me know if you find any thing more out.

**Comment by jbadeau** [comment]
I cannot do a pull request but the following changes were made to make this work in Rhino:

**r.js**

``` javascript
(function(define) {
define(['./builder/fs'], function(rhinofs) {

...

    function getFile(url, cb) {
        var file;

                // added support for rhino
        var fs = null;

        if(require.nodeRequire) {
            fs = require.nodeRequire('fs');
        }
        else {
            fs = rhinofs;
        }

        file = fs.readFileSync(url, 'utf8');
        // Remove BOM (Byte Mark Order) from utf8 files if it is there.
        if (file.indexOf('\uFEFF') === 0) {
            file = file.substring(1);
        }
        cb(file);
    }

});
}(typeof define === 'function' ? define : function(factory) { module.exports = factory(); }));
```

**fs.js**
from: dojo-release-1.8.3-src\util\build\rhino\fs.js

cheers
