### ISSUE TITLE
rjs Builder Plugin

### ISSUE THREAD

**Issue by eschwartz** [pieterv/rjs-wire#2]
This is regarding the [rjs builder plugin in your fork'd WireJS repo](https://github.com/pieter-vanderwerff/wire/blob/rjs-build/builder/rjs.js).

First off, thank you for this great plugin -- you really saved my butt! I'm learning the hard way that trying to build a library _before_ you put months of work into it is _probably_ a good idea... :)

I ran into a couple of minor issues when messing around with this plugin:
### Configuring the `childSpecRegex`

The plugin accepts config values for a `childSpecRegex`:

``` javascript
// rjs.js line 47
childSpecRegex = defaultSpecRegex;

if(config) {
  if(config.moduleRegex) { moduleRegex = new RegExp(config.moduleRegex); }
  if(config.childSpecRegex) { childSpecRegex = new RegExp(config.childSpecRegex); }
  if(config.wireId) { wireId = config.wireId; }
}
```

However, the `childSpecRegex` value is never used:

``` javascript
// r.js Line 161
function isWireDep(path) {
  return defaultSpecRegex.test(path);
}
```

I'm assuming the `isWireDep` method is supposed to reference the `childSpecRegex` here, not the `defaultSpecRegex`
### Modules defined in $plugin are not packaged

Consider the spec:

``` javascript
define({
  $plugins: [
    'plugin/MyAwesomePlugin',
    'plugin/AnotherReallyGreatPlugin'
  ]
});
```

These plugins will not be written to the build package. I tried changing the `moduleRegex` to  `/\.(module|create|\$plugins)$/;`, but it had no effect.

My workaround was to was use the full syntax for defining plugins in my specs:

``` javascript
define({
  $plugins: [
    { module: 'plugin/MyAwesomePlugin' },
    { module: 'plugin/AnotherReallyGreatPlugin' }
  ]
});
```

This was successful.

---

Again, thanks for the builder plugin. You might consider moving your plugin to its own repo -- it's being linked to by the [WireJS documentation](https://github.com/cujojs/wire/blob/master/docs/wire.md#amd-plugin), so I imagine a number of people are using it.

**Comment by pieterv** [comment]
Hey, thanks for your detailed issue!

As you suggested i have moved the plugin into its own repo, i had originally intended to submit a pull request but found it hard to do any nice unit testing so gave up :) Here it is: https://github.com/pieter-vanderwerff/wire-rjs-builder

In the new project repo i have fixed the issues you identified, plus did some general cleanup.

The `$plugins` includes should be working now, the regex you had was just a little off, it needed a little tweaking to fit in with the way the wire paths a expressed internally `/(\.module|\.create|\$plugins\[\])$/;`. With this change you should be able to have a mix of objects and strings within the `$plugins` array and it should pick them all up. See https://github.com/pieter-vanderwerff/rjs-wire/blob/master/fixture/spec1.js

Thanks again!

**Comment by eschwartz** [comment]
Awesome. Good stuff.
